import localFont from 'next/font/local'; // ini function expression
import "./styles/globals.css";
import Navbar from './components/navbar';

const marykate = localFont({ // ini object
  src: './fonts/Marykate-Regular.ttf',
  display: 'swap',
  variable: '--font-sans',
})

export const metadata = {
  title: "Dicky Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${marykate.variable} antialiased`}
      >
        <Navbar />
        <main className="p-6 bg-slate-900">{children}</main>
      </body>
    </html>
  );
}
