import localFont from 'next/font/local'; // ini function expression
import "./styles/globals.css";

const marykate = localFont({ // ini object
  src: './fonts/Marykate-Regular.ttf',
  display: 'swap',
  variable: '--font-sans',
})

export const metadata = {
  title: "Dicky Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${marykate.variable} antialiased`}
      >
      {children}
      </body>
    </html>
  );
}
