import localFont from 'next/font/local';
import "./globals.css";

const marykate = localFont({
  src: './fonts/marykate-regular.ttf',
  display: 'swap',
  variable: '--font-sans',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${marykate.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
